### PR TITLE
MAINT: Add larsoner as maintainer and automerge

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin please rerender

**Comment by larsoner** [comment]
I removed the build bump -- wasn't sure if I needed it but the `automerge` one for `mayavi` didn't have a bump so I'm guessing I don't need one here, either.

I also added bot automerge so that hopefully future version bumps can be merged automatically for us assuming they come back green.

Ready for review/merge from my end @grlee77 !

**Comment by larsoner** [comment]
@conda-forge-admin please rerender

**Review by grlee77 — APPROVED** [review]

**Comment by grlee77** [comment]
> I also added bot automerge so that hopefully future version bumps can be merged automatically for us assuming they come back green.

Ah, yeah that would be good. I didn't know that was now an option!

**Pull request merged**
